disabled_rules:
  - line_length
  - trailing_newline
  - trailing_whitespace
  - variable_name
  - type_name
  - todo
  - nesting

excluded:
  - Docs
  - Frameworks
  - Pods

variable_name_min_length: 1
variable_name_max_length: 40
function_body_length: 300
file_length: 800
type_body_length: 800
